services:
  web:
    image: ghcr.io/exuslight/gazelservices:latest
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Telegram__BotToken: ${TELEGRAM_BOT_TOKEN}
      Telegram__ChatId: ${TELEGRAM_CHAT_ID}
    restart: unless-stopped
